// Regenerates supabase/seed.sql from src/data/catalog.json (the starting catalog).
// Usage: npm run seed:sql
import { readFileSync, writeFileSync } from "node:fs";

const catalog = JSON.parse(readFileSync(new URL("../src/data/catalog.json", import.meta.url), "utf8"));

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (a) => (a.length ? `array[${a.map(q).join(", ")}]::text[]` : "'{}'::text[]");

const rows = catalog.map(
  (p, i) =>
    `  (${q(p.name)}, ${q(p.name_en)}, ${q(p.slug)}, ${q(p.category)}, ${p.price}, ${q(p.description)}, ${q(
      p.description_en
    )}, ${arr(p.options)}, ${p.featured}, ${p.sold}, ${arr(p.images)}, now() - interval '${i} minutes')`
);

const sql = `-- Starting catalog for Boushra (generated by scripts/generate-seed.mjs — do not edit by hand).
-- Prices are placeholders: adjust them from the admin dashboard.
insert into products (name, name_en, slug, category, price, description, description_en, options, featured, sold, images, created_at)
values
${rows.join(",\n")}
on conflict (slug) do update
  set name_en = coalesce(products.name_en, excluded.name_en),
      description_en = coalesce(products.description_en, excluded.description_en);
`;

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql);
console.log(`Wrote ${catalog.length} products to supabase/seed.sql`);
